### ISSUE TITLE
allowedlist, denylist of packages

### ISSUE THREAD

**Issue by sibelius** [Grohden/babel-plugin-resolve-barrel-files#1]
Can we just have

```
plugins: [
    [
      'resolve-barrel-files',
  ]
]
```

and apply this transform to all packages?

or using a regex pattern to define packages

**Comment by Grohden** [comment]
🤔 I'll explore that

For now you can collect and generate the list of mappings in the babel file:

```js
/// do some magic reading the package.json

const mappings = {}
dependencies.forEach(depName => {
  mapping[depName] = { moduleType: 'commonjs',  barrelFilePath: require.resolve(dep) } },
});
```

I also didn't wanted to make it auto because you can have paths inside of your sources (1) where you may want to remove barrels

1 - I have yet to test how this package works with import aliases

**Comment by sibelius** [comment]
we can get the barrelFilepath like this

```
const mainBarrelPath = require.resolve(moduleName, { basedir: cwd });
```

**Comment by sibelius** [comment]
one fewer config

maybe we can infer esm or commonjs some how

**Comment by Grohden** [comment]
> maybe we can infer esm or commonjs some how

I'm open to ideas; In theory that should be listed in the package.json of the package, maybe I can rely on that

I'll explore making the experience with this package better later at night
